services:
  mcp-server:
    build: .
    container_name: mcp_server_odoo
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # Odoo Connection Configuration
      # Replace these with your actual Odoo instance details
      - ODOO_URL=https://amf.f.arkana.app
      - ODOO_DB=amf

      # Authentication (choose one method):
      # Option 1: API Key (recommended)
      - ODOO_API_KEY=ca983fcc0d27b634a8da60b0a0a61205a25f4867
      # Option 2: Username and Password (uncomment and use if no API key)
      # - ODOO_USER=your_username
      # - ODOO_PASSWORD=your_password

      # MCP Server Configuration
      - ODOO_MCP_TRANSPORT=streamable-http
      - ODOO_MCP_HOST=0.0.0.0
      - ODOO_MCP_PORT=8000
      - ODOO_MCP_LOG_LEVEL=INFO

      # Optional: Performance settings
      - ODOO_MCP_DEFAULT_LIMIT=10
      - ODOO_MCP_MAX_LIMIT=100
    restart: "no"
    networks:
      nginx-proxy:
        ipv4_address: 172.20.0.98

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy